export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  ADMIN: 'ADMIN',
  FIREFIGHTER_TRAINEE: 'FIREFIGHTER_TRAINEE',
  CAPACITATOR: 'CAPACITATOR',
  MEDICAL: 'MEDICAL',
  RESEARCHER: 'RESEARCHER',
  FIRE_CHIEF: 'FIRE_CHIEF',
};
